- hosts: localhost
  connection: local
  gather_facts: no
  vars:
        pattern1: "200"
        pattern2: "404"
        admin_user: "admin"
        admin_password: "password"

  tasks:
   - name: check the status code
     uri:
          url: "https://test.restapiexample.com/app"
          method: GET
          user: "{{ admin_user }}"
          password: "{{ admin_password }}"
          status_code: 200,404
     register: response
   - local_action: "copy content='{{ response.status }}' dest=/root/status.txt"  

   - name: HTTP 200 status
     find:
        paths: /root/
        patterns: '*.txt'
        file_type: file
        contains: "{{ pattern1 }}"
     register: response_200

   - debug:
        msg: HTTP Status Code is 200 - connection success
      when: response_200.matched > 0

   - name: HTTP 404 status
     find:
        paths: /root/
        patterns: '*.txt'
        file_type: file
        contains: "{{ pattern2 }}"
     register: response_404
  
   - debug:
        msg: HTTP Status Code is 404 - connection failed
     when: response_404.matched > 0  
